### ISSUE TITLE
Final publishing

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#12]
This is the final step in the ui-library setup project

- [ ] Merge dev to staging. Then merge staging to main.
- [ ] Check that a new DRAFT release is created
- [ ] Edit the draft, then publish it.
- [ ] Check that the final packages are deployed to npm

Here's how we publish packages:

1. A PR is made against `staging`, it is reviewed and merged. The package is automatically published for testing.
2. Test test test. Then test again.
3. A PR is made against `main`, it is reviewed and merged. Upon merging, the action `ci-release.yml` will generate a [Github Release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) with status "DRAFT"
4. If the Release is published, then the action `publish-release.yml` will automatically publish the package.

- [ ] Please add the above documentation in the `keyp-app` under `docs/`. Feel free to edit and update it as needed.

**Comment by alekseevaiana** [comment]
## Plan
- Create a new branch called "staging" (no need to create PR, because I create branch from dev).
- Create a PR: `staging` branch against `main` branch.
- Check that a new DRAFT release is created. I can check this by going to the repository on GitHub and looking under the "Releases" tab.
- Edit the draft release if necessary.
- Test package before publishing.
- Publish the release if everything ok. This can be done by clicking the "Publish release" button on the draft release page.
- Check that the final packages are deployed to npm. I can do this by checking the npm registry to see if the new version of the package is available.

**Comment by pi0neerpat** [comment]
Sounds good!

**Comment by alekseevaiana** [comment]
I see I missed the last task:
> Please add the above documentation in the keyp-app under docs/. Feel free to edit and update it as needed.

@pi0neerpat you mean to include in `keyp-app/docs` one more .md file with instructions on how to publish packages? Or update `usekeyp-docs` with the `ui-library` chapter?

**Comment by pi0neerpat** [comment]
Update keyp-app/docs
