### ISSUE TITLE
Tailwind CSS ESM support

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#17]
See discussion here. 

https://github.com/UseKeyp/keyp-frontend-components/issues/42

Let's do this first in this repo. You can do this together with the precompile issue to improve DX for installing the package. Or you can do them as separate pull requests. 

Either way, please make another issue for the precompile DX improvements issue. Assign that issue to yourself, and add the appropriate project board and labels

**Comment by alekseevaiana** [comment]
Couldn't make a plan, because had to test it first:
- I was able to install the updated tailwindcss version and change cjs to js. 
- I created PR (without requesting review yet), and added the package to an outer project and it seems to work. Also found bugs, and improved them.
- Installed Flowbite package and saw how they use tailwind: if I understand correctly, they create plugin.js file that describes all their extended tailwind themes. Then users use it as a plugin in their tailwind.config.js. 
I am going to try it, it has to be more clear than merging two tailwind config files. At least you can find about plugins in tailwind documentation.
- Couldn't understand yet how to pre-build js files, so users don't have to change their webpack file, but I am close! 
- Will create another issue on how to precompile js files to improve DX, as soon as have a plan.
