### ISSUE TITLE
[SDK] 7. Research other tools

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#41]
Example interface design for various interfaces
Frontend: https://supertokens.com/docs/thirdparty/pre-built-ui/setup/frontend
Backend: https://supertokens.com/docs/thirdparty/pre-built-ui/setup/backend

- Websocket service?
- Notifications?

**Comment by pi0neerpat** [comment]
This is an open-ended issue to capture the discussion around other tools we can offer as part of the SDK. For instance, we can include the transaction notifications service from BlockNative as part of the SDK. Feel free to put any ideas here.

**Comment by jahabeebs** [comment]
Wallet recovery wizard: we could build some way to recover users' lost/hijacked wallets like here (https://github.com/BitGo/wallet-recovery-wizard) though once we decentralize it more it would probably deprecate itself (unless we decided to make some wallets more custodial/centralized than others). I think Coinbase uses this internally so should be possible to do with MPC

Multi-sigs: i'm not super knowledgeable about creating multi-sigs programmatically but we could offer some basic endpoints and helper functions for creating/managing a multi-sig w/gnosis safe's api. once we have gas wallets this will be more relevant because we'll need to allow users to refill gas wallets programmatically

Token swapping: can create helper functions/hooks for doing swaps through uniswap/sushiswap API

Websocket notifications: we can create helper functions for alchemy's subscription API (https://docs.alchemy.com/reference/subscription-api) and create endpoints that will let us email customers when certain events occur (like billing or getting a new user for example). the only thing is websockets tend to be really expensive so it would have to be billing based on a certain # of free events per month like what Vercel does

NFT marketplace: would be very cool to create functions/hooks to easily allow users to list NFTs to OpenSea using their API (I think we do this with TC?). This would be something that we could put on the UI and as hooks/functions in an SDK (like a listOnOpenSea.ts hook ) 

Gas price estimator: can wrap quicknode or blocknative's APIs with our own functions to allow users to easily estimate gas prices for a transaction before it happens. This would be important if they want to show users an estimate of what the cost of a particular transaction would be (and we'll probably have this in our own UI in some app as well when we're on networks that have significant gas costs)

Token value estimator: same things as gas price estimator but for the USD value of a particular token (I know we'll do this already on the back end for certain API functions but we should have a way for users to do their own calculation)

Analytics Dashboard: could create an analytics provider for react applications that has a built in, simple way to track an app's analytics (like Vercel's @vercel/analytics package). Not sure how they implement this exactly but we could let users view analytics on our front end and it could be a valuable service

Staking integrations: allow users to stake and unstake a coin programatically via our API and show it on the UI when they log into keyp app. easy way for users to gain interest on some coins that we support (blockdaemon seems like a good option for their API: https://www.blockdaemon.com/stake/staking-api)

**Comment by pi0neerpat** [comment]
These are all good ideas. Can you pick one you'd like to implement for next sprint and create an issue for it?

**Comment by pi0neerpat** [comment]
Closing since finished!
